---
- name: Install Docker
  tags: docker
  hosts: webservers
  become: true

  vars:
    dpkg_arch: {
      "armv6l": "armhf",
      "armv7l": "armhf",
      "aarch64": "arm64",
      "x86_64": "amd64",
      "i386": "i386"
    }

  tasks:
  - name: Create apt keyring
    ansible.builtin.file:
      name: /etc/apt/keyrings
      state: directory
      mode: '0755'
  - name: Add Docker GPG key (apt)
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: '0644'
  - name: Add Docker repository (apt)
    ansible.builtin.apt_repository:
      filename: docker
      repo: 'deb [arch={{ dpkg_arch[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release  }} stable'
      update_cache: true
  - name: Install Docker (apt)
    ansible.builtin.apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin